import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=s=>document.querySelector(s), scene=new THREE.Scene();
scene.background=new THREE.Color(0x82b9df);scene.fog=new THREE.Fog(0x82b9df,28,78);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,120);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1));renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdff4ff,0x4c3b2b,1.8));const sun=new THREE.DirectionalLight(0xfff0cf,2);sun.position.set(-30,50,20);scene.add(sun);
const world=new THREE.Group();scene.add(world),cube=new THREE.BoxGeometry(1,1,1),blocks=[],map=new Map(),chunks=new Map();
const defs={grass:['Трава','#5cae43'],dirt:['Земля','#795238'],stone:['Камень','#747a7b'],sand:['Песок','#d8c47d'],wood:['Дерево','#87562f'],leaves:['Листва','#3e8738'],coal:['Уголь','#33383a'],iron:['Железо','#a9a39a'],brick:['Кирпич','#a44f40'],planks:['Доски','#a56c3c']};
const mats={};
function makeTexture(type){const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.fillStyle=defs[type][1];x.fillRect(0,0,32,32);let seed=type.length*97;for(let i=0;i<70;i++){seed=(seed*1664525+1013904223)>>>0;const px=seed%32,py=(seed>>>8)%32;x.fillStyle=i%3?'#ffffff12':'#00000018';x.fillRect(px,py,1+(seed%4),1+(seed%4))}if(type==='grass'){x.fillStyle='#39862f';x.fillRect(0,0,32,5)}if(type==='coal'||type==='iron'){for(let i=0;i<7;i++){x.fillStyle=type==='coal'?'#17191a':'#d7d1c6';x.fillRect((i*13)%28,((i*7)+3)%28,3,3)}}const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;return t}
for(const k in defs)mats[k]=new THREE.MeshLambertMaterial({map:makeTexture(k)});
const items=['grass','dirt','stone','wood','leaves','sand','coal','iron','brick'];let selected=0;
const inv={grass:64,dirt:64,stone:64,wood:24,leaves:32,sand:32,coal:0,iron:0,brick:32};
const key=(x,y,z)=>`${x}|${y}|${z}`;const hash=(x,z)=>{const n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)};
function noise(x,z){return (Math.sin(x*.11)+Math.cos(z*.13)+Math.sin((x+z)*.055)*1.5)/3}
function terrain(x,z){let h=Math.floor(7+noise(x,z)*5+noise(x*.45,z*.45)*4);return Math.max(2,Math.min(16,h))}
function addBlock(x,y,z,type='grass',user=false){const k=key(x,y,z);if(map.has(k))return;const m=new THREE.Mesh(cube,mats[type]||mats.grass);m.position.set(x,y,z);m.userData={x,y,z,type,user};world.add(m);blocks.push(m);map.set(k,m);return m}
function delBlock(m){if(!m||m.userData.y<=0)return false;world.remove(m);map.delete(key(m.userData.x,m.userData.y,m.userData.z));const i=blocks.indexOf(m);if(i>=0)blocks.splice(i,1);return true}
function generateChunk(cx,cz){const ck=`${cx},${cz}`;if(chunks.has(ck))return;const startX=cx*16,startZ=cz*16;for(let x=0;x<16;x++)for(let z=0;z<16;z++){const wx=startX+x,wz=startZ+z,h=terrain(wx,wz);for(let y=0;y<=h;y++){let t=y===h?(h<5?'sand':'grass'):y>=h-3?'dirt':'stone';const r=hash(wx*3+y,wz*7-y);if(y>2&&y<h-2&&r>.975)t='coal';else if(y>3&&y<h-3&&r<.018)t='iron';addBlock(wx,y,wz,t,false)}if(hash(wx+91,wz-17)>.965&&h>6){for(let y=1;y<=4;y++)addBlock(wx,h+y,wz,'wood',false);for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=3;dy<=5;dy++)if(Math.abs(dx)+Math.abs(dz)+Math.abs(dy-4)<4)addBlock(wx+dx,h+dy,wz+dz,'leaves',false)}}chunks.set(ck,true)}
function removeFar(cx,cz){for(const [ck] of chunks){const [x,z]=ck.split(',').map(Number);if(Math.abs(x-cx)>renderDistance+1||Math.abs(z-cz)>renderDistance+1){for(let i=blocks.length-1;i>=0;i--){const b=blocks[i];if(Math.floor(b.userData.x/16)===x&&Math.floor(b.userData.z/16)===z){world.remove(b);map.delete(key(b.userData.x,b.userData.y,b.userData.z));blocks.splice(i,1)}}chunks.delete(ck)}}}
let renderDistance=3;function stream(){const cx=Math.floor(player.pos.x/16),cz=Math.floor(player.pos.z/16);for(let x=-renderDistance;x<=renderDistance;x++)for(let z=-renderDistance;z<=renderDistance;z++)generateChunk(cx+x,cz+z);removeFar(cx,cz);return [cx,cz]}
const player={pos:new THREE.Vector3(0,terrain(0,6)+1.7,6),yaw:0,pitch:0,vy:0,ground:false};camera.position.copy(player.pos);camera.add(new THREE.Mesh(new THREE.BoxGeometry(.22,.22,.62),new THREE.MeshLambertMaterial({color:0xc98c68})));camera.children[0].position.set(.42,-.38,-.62);scene.add(camera);
const keys={};let started=false,paused=false,guiOpen=false,invOpen=false,target=null,lastChunk='';
const menu=$('#menu'),pause=$('#pause'),gui=$('#clickgui'),inventory=$('#inventory');
function renderHotbar(){const h=$('#hotbar');h.innerHTML=items.map((t,i)=>`<div class="slot ${i===selected?'selected':''}" data-i="${i}"><div class="swatch" style="background:${defs[t][1]}"></div><em>${i+1}</em></div>`).join('');h.querySelectorAll('.slot').forEach(s=>s.onclick=()=>{selected=+s.dataset.i;renderHotbar()})}
function renderInv(){const g=$('#invGrid');g.innerHTML=items.concat(items).map(t=>`<div class="inv-slot" title="${defs[t][0]}: ${inv[t]||0}"><div class="swatch" style="background:${defs[t][1]}"></div></div>`).join('')}
renderHotbar();renderInv();
function lock(){if(started&&!paused&&!guiOpen&&!invOpen)renderer.domElement.requestPointerLock?.()}function toggleGui(){guiOpen=!guiOpen;gui.classList.toggle('hidden',!guiOpen);if(guiOpen)document.exitPointerLock?.();else lock()}function toggleInv(){invOpen=!invOpen;inventory.classList.toggle('hidden',!invOpen);if(invOpen)document.exitPointerLock?.();else lock()}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape'){if(guiOpen){toggleGui();return}if(invOpen){toggleInv();return}if(started){paused=!paused;pause.classList.toggle('hidden',!paused);if(paused)document.exitPointerLock?.();else lock()}}if(e.code==='ShiftRight'&&!paused)toggleGui();if(e.code==='KeyE'&&!paused)toggleInv();if(/^Digit[1-9]$/.test(e.code)){selected=+e.code.slice(-1)-1;renderHotbar()}});addEventListener('keyup',e=>keys[e.code]=false);
$('#play').onclick=()=>{started=true;menu.classList.add('hidden');lock()};$('#resume').onclick=()=>{paused=false;pause.classList.add('hidden');lock()};$('#save').onclick=()=>saveWorld();
addEventListener('mousedown',e=>{if(!started||paused||guiOpen||invOpen)return;if(document.pointerLockElement!==renderer.domElement){lock();return}if(e.button===0)breakBlock();if(e.button===2)placeBlock()});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement||paused||guiOpen||invOpen)return;player.yaw-=e.movementX*.0022;player.pitch=Math.max(-1.52,Math.min(1.52,player.pitch-e.movementY*.0022))});addEventListener('wheel',e=>{selected=(selected+(e.deltaY>0?1:-1)+items.length)%items.length;renderHotbar()});
const ray=new THREE.Raycaster(),center=new THREE.Vector2();function getTarget(){ray.setFromCamera(center,camera);return ray.intersectObjects(blocks,false).find(h=>h.distance<6)}
function breakBlock(){const h=getTarget();if(!h)return;const b=h.object;if(delBlock(b)){inv[b.userData.type]=(inv[b.userData.type]||0)+1;renderInv();saveWorld()}}
function placeBlock(){const h=getTarget();if(!h)return;const t=items[selected];if((inv[t]||0)<=0)return;const p=h.object.position.clone().add(h.face);const x=Math.round(p.x),y=Math.round(p.y),z=Math.round(p.z);if(Math.abs(x-player.pos.x)<.8&&Math.abs(z-player.pos.z)<.8&&Math.abs(y-player.pos.y)<2)return;if(addBlock(x,y,z,t,true)){inv[t]--;renderInv();saveWorld()}}
function solidAt(x,y,z){const b=map.get(key(Math.floor(x),Math.floor(y),Math.floor(z)));return !!b&&b.userData.type!=='leaves'}
function groundAt(x,z){for(let y=Math.floor(player.pos.y)+2;y>=0;y--)if(solidAt(x,y,z))return y+1;return 0}
function move(dt){if(!started||paused||guiOpen||invOpen)return;const dir=new THREE.Vector3();if(keys.KeyW)dir.z--;if(keys.KeyS)dir.z++;if(keys.KeyA)dir.x--;if(keys.KeyD)dir.x++;if(dir.lengthSq())dir.normalize();dir.applyAxisAngle(new THREE.Vector3(0,1,0),player.yaw);const speed=keys.ShiftLeft?7:4.5;let nx=player.pos.x+dir.x*speed*dt,nz=player.pos.z+dir.z*speed*dt;const r=.28;if(!solidAt(nx+r,player.pos.y-1.5,player.pos.z)&&!solidAt(nx-r,player.pos.y-1.5,player.pos.z))player.pos.x=nx;if(!solidAt(player.pos.x,player.pos.y-1.5,nz+r)&&!solidAt(player.pos.x,player.pos.y-1.5,nz-r))player.pos.z=nz;const g=groundAt(Math.floor(player.pos.x),Math.floor(player.pos.z));if(keys.Space&&player.ground){player.vy=6;player.ground=false}player.vy-=17*dt;player.pos.y+=player.vy*dt;if(player.pos.y<=g+1.65){player.pos.y=g+1.65;player.vy=0;player.ground=true}if(player.pos.y<1)player.pos.y=1.65;camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0)}
function saveWorld(){const data=[];for(const b of blocks)if(b.userData.user)data.push([b.userData.x,b.userData.y,b.userData.z,b.userData.type]);localStorage.setItem('golo-world',JSON.stringify(data))}
function loadWorld(){try{const data=JSON.parse(localStorage.getItem('golo-world')||'[]');for(const b of data)addBlock(b[0],b[1],b[2],b[3],true)}catch{}}
const modules={blockEsp:true,oreEsp:true,tracers:false,hud:true};document.querySelectorAll('[data-m]').forEach(i=>i.onchange=()=>modules[i.dataset.m]=i.checked);$('#boost').onchange=e=>scene.fog.far=e.target.checked?65:100;$('#distance').oninput=e=>{renderDistance=+e.target.value;$('#distanceValue').textContent=renderDistance};
const esp=document.createElement('canvas');esp.style.cssText='position:fixed;inset:0;width:100%;height:100%;pointer-events:none;z-index:9';document.body.appendChild(esp);const ec=esp.getContext('2d');function drawESP(){ec.clearRect(0,0,innerWidth,innerHeight);if(!modules.blockEsp&&!modules.oreEsp&&!modules.tracers)return;for(const b of blocks){const ore=b.userData.type==='coal'||b.userData.type==='iron';if(ore&&!modules.oreEsp||!ore&&!modules.blockEsp)continue;const p=b.position.clone().project(camera);if(p.z<0||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1)continue;const x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;ec.strokeStyle=ore?'#42d9ff':'#79d34d';ec.globalAlpha=ore?1:.28;ec.strokeRect(x-6,y-6,12,12);if(modules.tracers&&ore){ec.beginPath();ec.moveTo(innerWidth/2,innerHeight/2);ec.lineTo(x,y);ec.stroke()}}ec.globalAlpha=1}
let day=0,fps=0,frames=0,ft=performance.now(),last=ft;function animate(t){requestAnimationFrame(animate);const dt=Math.min(.05,(t-last)/1000);last=t;frames++;if(t-ft>500){fps=Math.round(frames*1000/(t-ft));frames=0;ft=t}move(dt);if(started&&!paused&&!guiOpen&&!invOpen){const c=stream().join(',');if(c!==lastChunk)lastChunk=c}day=(day+dt*.015)%1;const ang=day*Math.PI*2;sun.position.set(Math.cos(ang)*45,Math.sin(ang)*45,20);const daylight=Math.max(.12,Math.sin(ang)*.5+.5);sun.intensity=1.1+daylight;scene.background.setHSL(.56,.45,.25+.28*daylight);scene.fog.color.copy(scene.background);const h=Math.floor(day*24),m=Math.floor((day*24-h)*60);$('#time').textContent=(daylight>.35?'☀':'☾')+` ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;renderer.render(scene,camera);drawESP();target=getTarget();if(target)$('#target').textContent='Блок: '+defs[target.object.userData.type][0];else $('#target').textContent='Блок: —';$('#debug').innerHTML=`FPS: ${fps}<br>XYZ: ${player.pos.x.toFixed(1)} ${player.pos.y.toFixed(1)} ${player.pos.z.toFixed(1)}<br>CHUNK: ${Math.floor(player.pos.x/16)} ${Math.floor(player.pos.z/16)}`;$('#hud').style.display=modules.hud?'block':'none'}
stream();loadWorld();setTimeout(()=>$('#loading').remove(),450);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);esp.width=innerWidth;esp.height=innerHeight});requestAnimationFrame(animate);
