import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const $=s=>document.querySelector(s),scene=new THREE.Scene();scene.background=new THREE.Color(0x79a9cf);
const camera=new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.05,180);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.appendChild(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xd8efff,0x584630,1.5);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe8bd,1.8);sun.position.set(-35,55,20);scene.add(sun);const world=new THREE.Group();scene.add(world);
const defs={grass:['Трава','#579b3e'],dirt:['Земля','#70492e'],stone:['Камень','#696d6e'],sand:['Песок','#cfb76d'],wood:['Бревно','#76502f'],leaves:['Листва','#347532'],coal:['Уголь','#25282a'],iron:['Железо','#918c85'],planks:['Доски','#9a6838'],brick:['Кирпич','#97483c'],water:['Вода','#286ba8']};
const hot=['grass','dirt','stone','wood','leaves','sand','planks','brick','coal'];let selected=0;const inv={grass:64,dirt:64,stone:64,wood:20,leaves:32,sand:32,planks:32,brick:16,coal:0,iron:0};
const CS=16,CH=24,R=2,chunks=new Map(),edited=new Map(),key=(x,y,z)=>`${x},${y},${z}`;function hash(x,z){const n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)}function noise(x,z){return(Math.sin(x*.09)+Math.cos(z*.12)+Math.sin((x+z)*.045)*1.5)/3}function height(x,z){return Math.max(3,Math.min(CH-3,Math.floor(8+noise(x,z)*4+Math.sin(x*.025)*2+Math.cos(z*.018)*2)))}
function base(x,y,z){const h=height(x,z);if(y>h)return'air';if(y===h)return h<6?'sand':'grass';if(y>=h-3)return'dirt';const r=hash(x*7+y*13,z*5-y*3);if(y>2&&r>.982)return'coal';if(y>4&&r<.014)return'iron';return'stone'}
function tree(x,z){return hash(x+71,z-33)>.968&&height(x,z)>7}function block(x,y,z){const k=key(x,y,z);if(edited.has(k))return edited.get(k);let t=base(x,y,z);if(t!=='air')return t;for(let tx=x-2;tx<=x+2;tx++)for(let tz=z-2;tz<=z+2;tz++)if(tree(tx,tz)){const h=height(tx,tz),dx=x-tx,dz=z-tz;if(x===tx&&z===tz&&y>h&&y<=h+4)return'wood';if(y>=h+3&&y<=h+5&&Math.abs(dx)+Math.abs(dz)<3)return'leaves';if(y===h+2&&Math.abs(dx)<=1&&Math.abs(dz)<=1)return'leaves'}return'air'}
function setBlock(x,y,z,t){if(y<0||y>=CH)return;if(t===base(x,y,z))edited.delete(key(x,y,z));else edited.set(key(x,y,z),t);saveWorld()}
function tex(hex,type){const c=document.createElement('canvas');c.width=c.height=16;const g=c.getContext('2d');g.fillStyle=hex;g.fillRect(0,0,16,16);let s=type.length*193+17;for(let i=0;i<28;i++){s=(s*1664525+1013904223)>>>0;g.fillStyle=i%4?'#ffffff16':'#00000018';g.fillRect(s%16,(s>>>8)%16,1+s%3,1+s%3)}if(type==='grass'){g.fillStyle='#3b8733';g.fillRect(0,0,16,4)}if(type==='coal'||type==='iron'){g.fillStyle=type==='coal'?'#111':'#ddd';for(let i=0;i<4;i++)g.fillRect((i*7+2)%13,(i*5+2)%13,2,2)}const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;return t}
const mats=Object.fromEntries(Object.entries(defs).map(([k,d])=>[k,new THREE.MeshLambertMaterial({map:tex(d[1],k)})]));
const faceVerts=[[[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[ -.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5],[-.5,.5,-.5]],[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,.5]],[[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],[[.5,-.5,-.5],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5]]];
const normals=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];
function build(cx,cz){const id=`${cx},${cz}`,old=chunks.get(id);if(old){world.remove(old);old.geometry.dispose()}const p=[],n=[],u=[],groups=[];let tri=0;const addFace=(wx,y,wz,fi,type)=>{const vs=faceVerts[fi],no=normals[fi],start=p.length/3;for(const v of vs){p.push(wx+v[0],y+v[1]+.5,wz+v[2]);n.push(...no);u.push(v[0]+.5,v[1]+.5)}groups.push({start:start*3,count:6*3,mat:Object.keys(defs).indexOf(type)});tri+=2};for(let x=0;x<CS;x++)for(let z=0;z<CS;z++){const wx=cx*CS+x,wz=cz*CS+z;for(let y=0;y<CH;y++){const t=block(wx,y,wz);if(t==='air'||!mats[t])continue;for(let f=0;f<6;f++){const q=normals[f];if(block(wx+q[0],y+q[1],wz+q[2])==='air')addFace(wx,y,wz,f,t)}}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(u,2));for(const q of groups)g.addGroup(q.start,q.count,q.mat);const mesh=new THREE.Mesh(g,Object.values(mats));mesh.userData.chunk=id;world.add(mesh);chunks.set(id,mesh)}
function stream(){const cx=Math.floor(player.pos.x/CS),cz=Math.floor(player.pos.z/CS);for(let x=-R;x<=R;x++)for(let z=-R;z<=R;z++)if(!chunks.has(`${cx+x},${cz+z}`))build(cx+x,cz+z);for(const [id,m] of chunks){const[a,b]=id.split(',').map(Number);if(Math.abs(a-cx)>R||Math.abs(b-cz)>R){world.remove(m);m.geometry.dispose();chunks.delete(id)}}}
function rebuild(x,z){const cx=Math.floor(x/CS),cz=Math.floor(z/CS);for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)build(cx+a,cz+b)}
const ray=new THREE.Raycaster(),center=new THREE.Vector2();function hit(){ray.setFromCamera(center,camera);let best=null;for(const m of chunks.values()){const h=ray.intersectObject(m,false)[0];if(h&&h.distance<6&&(!best||h.distance<best.distance))best=h}return best}
function breakBlock(){const h=hit();if(!h)return;const p=h.point.clone().addScaledVector(h.face,-.03),x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z),t=block(x,y,z);if(t==='air'||y<=0)return;setBlock(x,y,z,'air');inv[t]=(inv[t]||0)+1;render();rebuild(x,z)}
function placeBlock(){const h=hit();if(!h)return;const p=h.point.clone().addScaledVector(h.face,.08),x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z),t=hot[selected];if((inv[t]||0)<=0||block(x,y,z)!=='air')return;if(Math.abs(x-player.pos.x)<.7&&Math.abs(z-player.pos.z)<.7&&Math.abs(y-player.pos.y)<2)return;setBlock(x,y,z,t);inv[t]--;render();rebuild(x,z)}
const player={pos:new THREE.Vector3(.5,height(0,6)+2,6.5),yaw:0,pitch:0,vy:0,ground:false};camera.position.copy(player.pos);
const keys={};let started=false,paused=false,guiOpen=false,invOpen=false,day=.25,fps=0,frames=0,ft=performance.now(),last=ft;
function renderHotbar(){$('#hotbar').innerHTML=hot.map((t,i)=>`<div class="slot ${i===selected?'selected':''}" data-i="${i}"><i style="background:${defs[t][1]}"></i><b>${i+1}</b><small>${inv[t]||0}</small></div>`).join('');document.querySelectorAll('.slot').forEach(e=>e.onclick=()=>{selected=+e.dataset.i;renderHotbar()})}function renderInv(){$('#invGrid').innerHTML=Object.keys(inv).map(t=>`<div class="invslot"><i style="background:${defs[t][1]}"></i><span>${defs[t][0]}</span><b>${inv[t]||0}</b></div>`).join('')}function render(){renderHotbar();renderInv()}
function saveWorld(){localStorage.setItem('golo-edits',JSON.stringify([...edited]));localStorage.setItem('golo-inv',JSON.stringify(inv))}function loadWorld(){try{for(const q of JSON.parse(localStorage.getItem('golo-edits')||'[]'))edited.set(q[0],q[1]);Object.assign(inv,JSON.parse(localStorage.getItem('golo-inv')||'{}'))}catch{}}
function lock(){if(started&&!paused&&!guiOpen&&!invOpen)renderer.domElement.requestPointerLock?.()}function gui(){guiOpen=!guiOpen;$('#clickgui').classList.toggle('hidden',!guiOpen);guiOpen?document.exitPointerLock?.():lock()}function inventory(){invOpen=!invOpen;$('#inventory').classList.toggle('hidden',!invOpen);invOpen?document.exitPointerLock?.():lock()}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape'){if(guiOpen){gui();return}if(invOpen){inventory();return}if(started){paused=!paused;$('#pause').classList.toggle('hidden',!paused);paused?document.exitPointerLock?.():lock()}}if(e.code==='ShiftRight'&&!paused)gui();if(e.code==='KeyE'&&!paused)inventory();if(/^Digit[1-9]$/.test(e.code)){selected=+e.code.slice(-1)-1;renderHotbar()}});addEventListener('keyup',e=>keys[e.code]=false);
$('#play').onclick=()=>{started=true;$('#menu').classList.add('hidden');lock()};$('#resume').onclick=()=>{paused=false;$('#pause').classList.add('hidden');lock()};$('#save').onclick=()=>{saveWorld();$('#saved').textContent='СОХРАНЕНО ✓';setTimeout(()=>$('#saved').textContent='',1300)};
addEventListener('mousedown',e=>{if(!started||paused||guiOpen||invOpen)return;if(document.pointerLockElement!==renderer.domElement){lock();return}if(e.button===0)breakBlock();if(e.button===2)placeBlock()});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement||paused||guiOpen||invOpen)return;player.yaw-=e.movementX*.0022;player.pitch=Math.max(-1.5,Math.min(1.5,player.pitch-e.movementY*.0022))});addEventListener('wheel',e=>{selected=(selected+(e.deltaY>0?1:-1)+hot.length)%hot.length;renderHotbar()});
function solid(x,y,z){const t=block(Math.floor(x),Math.floor(y),Math.floor(z));return t!=='air'&&t!=='leaves'&&t!=='water'}function move(dt){if(!started||paused||guiOpen||invOpen)return;const d=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(d.lengthSq()){d.normalize();d.applyAxisAngle(new THREE.Vector3(0,1,0),player.yaw);const sp=keys.ShiftLeft?7:4.3,nx=player.pos.x+d.x*sp*dt,nz=player.pos.z+d.z*sp*dt;if(!solid(nx,player.pos.y-1.3,player.pos.z)&&!solid(nx,player.pos.y-.2,player.pos.z))player.pos.x=nx;if(!solid(player.pos.x,player.pos.y-1.3,nz)&&!solid(player.pos.x,player.pos.y-.2,nz))player.pos.z=nz}let g=0;for(let y=Math.floor(player.pos.y);y>=0;y--)if(solid(player.pos.x,y,player.pos.z)){g=y+1;break}if(keys.Space&&player.ground){player.vy=6.3;player.ground=false}player.vy-=17*dt;player.pos.y+=player.vy*dt;if(player.pos.y<=g+1.7){player.pos.y=g+1.7;player.vy=0;player.ground=true}camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0)}
const modules={blockEsp:true,oreEsp:true,tracers:false,hud:true};document.querySelectorAll('[data-m]').forEach(i=>i.onchange=()=>modules[i.dataset.m]=i.checked);$('#distance').oninput=e=>$('#distanceValue').textContent=e.target.value;$('#boost').onchange=e=>renderer.setPixelRatio(e.target.checked?1:Math.min(devicePixelRatio,1.5));
const esp=document.createElement('canvas');esp.className='esp';document.body.appendChild(esp);const ec=esp.getContext('2d');function drawESP(){esp.width=innerWidth;esp.height=innerHeight;ec.clearRect(0,0,innerWidth,innerHeight);const h=hit();if(!h)return;const p=h.point.clone().project(camera),x=(p.x*.5+.5)*innerWidth,y=(-p.y*.5+.5)*innerHeight;ec.strokeStyle='#9cf06b';ec.lineWidth=2;ec.strokeRect(x-11,y-11,22,22);if(modules.tracers){ec.beginPath();ec.moveTo(innerWidth/2,innerHeight/2);ec.lineTo(x,y);ec.stroke()}}
function animate(t){requestAnimationFrame(animate);const dt=Math.min(.05,(t-last)/1000);last=t;frames++;if(t-ft>500){fps=Math.round(frames*1000/(t-ft));frames=0;ft=t}move(dt);if(started&&!paused&&!guiOpen&&!invOpen)stream();day=(day+dt*.006)%1;const a=day*Math.PI*2,light=Math.max(.1,Math.sin(a)*.5+.5);sun.position.set(Math.cos(a)*55,Math.sin(a)*55,25);sun.intensity=.5+1.7*light;hemi.intensity=.7+.8*light;scene.background.setHSL(.57,.42,.22+.32*light);$('#time').textContent=(light>.32?'☀':'☾')+' '+String(Math.floor(day*24)).padStart(2,'0')+':'+String(Math.floor(day*1440)%60).padStart(2,'0');$('#debug').innerHTML=`FPS: ${fps}<br>XYZ: ${player.pos.x.toFixed(1)} ${player.pos.y.toFixed(1)} ${player.pos.z.toFixed(1)}<br>CHUNK: ${Math.floor(player.pos.x/16)} ${Math.floor(player.pos.z/16)}`;const h=hit();$('#target').textContent=h?'ЛКМ ломать • ПКМ ставить':'Блок: —';$('#hud').style.display=modules.hud?'block':'none';renderer.render(scene,camera);drawESP()}
render();loadWorld();stream();setTimeout(()=>$('#loading')?.remove(),500);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);esp.width=innerWidth;esp.height=innerHeight});requestAnimationFrame(animate);
